// app/layout.js
import './globals.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}





// import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';
// import Headerx from './Components/Header';

// const geistSans = Geist({
//   subsets: ['latin'],
//   variable: '--font-geist-sans',
// });

// const geistMono = Geist_Mono({
//   subsets: ['latin'],
//   variable: '--font-geist-mono',
// });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//        < Headerx/>
//         {children}
//       </body>
//     </html>
//   );
// }
